#!/bin/bash

if [ $(uname -s) = 'Darwin' ]; then
  echo "Manual install for vscode on osx ..."
  mkdir -p "$HOME/Library/Application Support/VSCode/User/"
  ln -sf $HOME/.dotfiles/vscode/settings.json "$HOME/Library/Application Support/VSCode/User/settings.json"
  ln -sf $HOME/.dotfiles/vscode/keybindings.json "$HOME/Library/Application Support/VSCode/User/keybindings.json"
  ln -sf $HOME/.dotfiles/vscode/snipppets "$HOME/Library/Application Support/VSCode/User/snipppets"
fi



code --install-extension ms-vscode.atom-keybindings
code --install-extension equinusocio.vsc-community-material-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension digitalbrainstem.javascript-ejs-support
code --install-extension craigmaslowski.erb
code --install-extension dbaeumer.vscode-eslint
code --install-extension orta.vscode-jest
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mechatroner.rainbow-csv
code --install-extension blanu.vscode-styled-jsx
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension silvenon.mdx
